### ISSUE TITLE
When will sysrepo-CPP be released? 

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo-cpp#4]
Hi,
     When will sysrepo-CPP be released? Is master available now?
Best regards.
thanks

**Comment by syyyr** [comment]
Hi,

currently, a lot of the functionality has already been implemented, most of our internal projects have been ported to sysrepo-cpp. Depending on your use-case, you might already be able to use the bindings. I'm currently in the middle of improving the documentation, so that might answer some of your questions about usage. If some functionality is missing, please let me know.

About actual *realeases*, I'm not sure when/if we're able to do that anytime soon. Hopefully @jktjkt can answer that.

**Comment by jktjkt** [comment]
@rydy, I suggest to start using our `master` branch, it's ready for general use. You'll need `devel` of `libyang` and `sysrepo`. We need to discuss a release process, so just be advised that we have not committed to API/ABI stability yet.

**Comment by rydy** [comment]
> @rydy, I suggest to start using our `master` branch, it's ready for general use. You'll need `devel` of `libyang` and `sysrepo`. We need to discuss a release process, so just be advised that we have not committed to API/ABI stability yet.

I see. Thank you
